export const Products = [
    "Azuro",
    "Black&White",
    "C.George",
    "Camouglage",
    "Candy",
    "Choco",
    "Christmas Wish",
    "Cornelia Pinky",
    "Forest",
    "Fuchsia and orange",
    "Galaxy",
    "GBOh",
    "Greanleaf",
    "HVN",
    "Marion",
    "Pastel",
    "Pink marmol",
    "S.Sea",
    "Sea Salmon",
    "Sea",
    "Sky",
    "Unicorn",
    "Viva España"
];