export const Products = [
    "Azzuro",
    "Black&White",
    "C.George",
    "Camouflage",
    "Candy",
    "Choco",
    "Christmas Wish",
    "Cornelia Pinky",
    "Forest",
    "Fuchsia and orange",
    "Galaxy",
    "GBOh",
    "Greenleaf",
    "HVN",
    "Marion",
    "Pastel",
    "Pink Marmol",
    "S.Sea",
    "Sea Salmon",
    "Sea",
    "Sky",
    "Unicorn",
    "Viva España"
];